version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "dependabot[bot]"
    commit-message:
      prefix: "⬆️ "
    labels:
      - "dependencies"
    reviewers:
      - "mayankpatibandla"
    target-branch: "develop"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "dependabot[bot]"
    commit-message:
      prefix: "⬆️ "
    labels:
      - "dependencies"
    reviewers:
      - "mayankpatibandla"
    target-branch: "develop"
