repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: mixed-line-ending
        args: [--fix=lf]
        exclude: "^dist/"
      - id: end-of-file-fixer
        exclude: "^dist/"
      - id: detect-private-key
      - id: check-yaml
      - id: check-vcs-permalinks
      - id: check-merge-conflict
      - id: check-json
      - id: check-case-conflict
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: npm-build
        name: Build js files
        entry: npm run build
        language: system
        pass_filenames: false
